#!/bin/bash

cp /etc/resolv.conf /etc/resolv.conf.old && \

sed -i 's/nameserver 10.17.1.14/nameserver 10.17.3.181/g' /etc/resolv.conf && \
sed -i 's/nameserver 10.17.1./nameserver 10.17.3.181/g' /etc/resolv.conf && \


cat /etc/resolv.conf
